version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    on-failure: ABORT
    commands:
      - echo Prebuild phase
      - npm install
      - npm run test
  build:
    on-failure: ABORT
    commands:
      - echo Build phase
      - npm run build:test
      - ls -al ./dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist/store-app-front-end/
